# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: letsbe-semantic-release

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - 'node_modules/**'
      - '.github/**'
    branches: [
      'develop'
    ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Semantic-release
        run: npx semantic-release@21.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_NPM_TOKEN }}
